title = Lord of the Test: Legacy
author = Minetest-LOTR Team
description = Experimental fork of LOTT - A subgame inspired by LOTR elements. Explore the world of Middle-Earth.
allowed_mapgens = singlenode